name: Docker build and push
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0"

env:
  DOCKER_BUILDKIT: 1

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        ruby: [
          '2.5',
          '2.6',
          '2.7'
        ]
        fedora: [34]

    steps:
      - uses: actions/checkout@v3

      - name: Set image name
        run: |
          echo "DOCKER_IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ruby" >> ${GITHUB_ENV}

      - name: render docker-compose.yml
        run: RUBY_VERSION=${{ matrix.ruby }} FEDORA_VERSION=${{ matrix.fedora }} envsubst <  docker-compose.yml.tmpl >  docker-compose.yml

      - name: Build image
        run: docker-compose -f docker-compose.yml build ruby

      - name: Tag image
        run: |
          docker tag ruby-fedora:${{ matrix.ruby }} ${DOCKER_IMAGE}:${{ matrix.ruby }}
          docker tag ruby-fedora:${{ matrix.ruby }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ github.run_number }}

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ github.run_number }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_NOTIFY_SLACK }}
          SLACK_COLOR: green
          SLACK_MESSAGE: 'Good luck, this time... :rocket:'
          SLACK_TITLE: Build successful

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.BUILD_NOTIFY_SLACK }}
          SLACK_COLOR: red
          SLACK_MESSAGE: 'Seems whatever you did failed :unrocket:'
          SLACK_TITLE: Build failed
