name: Docker build and push
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 2 * * 0"

env:
  DOCKER_BUILDKIT: 1
  FEDORA_VERSION: 35

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        ruby: [
          '2.7',
          '3.0'
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          config: hadolint-ci.yaml

      - name: Set image name
        run: |
          echo "DOCKER_IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/ruby" >> ${GITHUB_ENV}

      - name: Render docker-compose.yml
        run: RUBY_VERSION=${{ matrix.ruby }} envsubst <  docker-compose.yml.tmpl >  docker-compose.yml

      - name: Build images
        run: docker-compose -f docker-compose.yml build

      - name: Tag image
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker tag ruby:${{ matrix.ruby }} ${DOCKER_IMAGE}:${{ matrix.ruby }}
          docker tag ruby:${{ matrix.ruby }} ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ github.run_number }}
          docker tag ruby:${{ matrix.ruby }}-jemalloc ${DOCKER_IMAGE}:${{ matrix.ruby }}-jemalloc
          docker tag ruby:${{ matrix.ruby }}-jemalloc ${DOCKER_IMAGE}:${{ matrix.ruby }}-jemalloc-${{ github.run_number }}

      - name: Log into registry
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-${{ github.run_number }}
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-jemalloc
          docker push ${DOCKER_IMAGE}:${{ matrix.ruby }}-jemalloc-${{ github.run_number }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: green
          SLACK_MESSAGE: 'Good luck, this time... :rocket:'
          SLACK_TITLE: Build successful

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: red
          SLACK_MESSAGE: 'Seems whatever you did failed :unrocket:'
          SLACK_TITLE: Build failed
